language: ruby
rvm: 2.0.0
before_install:
- travis_retry gem install bitballoon
- travis_retry gem install jekyll
- travis_retry gem install jekyll-assets
script: jekyll build
after_success: bitballoon deploy _site --access-token=$BB_ACCESS_TOKEN --site-id=$BB_SITE_ID
branches:
  only:
  - master
env:
  global:
  - secure: Rogy/KsDSxaMni713cO+Hv+lybrWEX6f0w9LZozd8FiytUwNXIqEnJg1lkuWv5c5JZLIqzMdCkw3Nr+aSna+WwKhLVazGUJ9KZJCySjtGqeFHD9Fmz/Jm+0xwb8qCGuV21EO642Et7tZJnHWqVgO16o3VB7ZolkXccbSQdLSZORNO7zc1fbAbLvf44H7KncCbz6bEtb8k/Jvzn3HSlmonaJp5BAXoTN4LjOwfkr3MMEpDdVCDyHEnSfesTAD4CGZA9sCq1NIrw5fQaUFA8L8uUxgIWeRiEoKCK1LtG4N69hJXwuw8apxd3hyl2qPddcdNd/3r9cmVwNI85YNYMtl1mytl2QLZGTo5XX+FEq9FXOwMVaVMY1X8VloqGYQkJRvNJ2iH9JZaqTq1+QUaPE+9hy4zHkSH2/OYXHDW7riCMCCQwnNZUX1t5FY98J5YWPJJLRTVjF6FWrV+n6LdORU/GOgXtMLsoR/tXla6UKGEFq+cYCDuIJ38PhEn+VA+aMwUY8qUvl0HPoG7fO1y0Ap0th2nCUGC95PIWfDHC45bIEg8Fs/OMdUBVDZjh7aycAGtNrMnMVuypQ8/i/tcZKFzdPASd3oXigkEBo6mupNed7lKXLX+j817qWvEpB5pqUJMMV5JtTUf9FgliCr1jvEb/ZrFTqtC2N8JFCpuTwTcIA=
  - secure: kiyMb7NEA6114wNFt4cpblpQGgJE+Gge6vm+dDACNjZyWNq5y6cm1gb+nFP7nrxGjxqnn2kBS7jqE5IyEIei1TQXaA1hOdNKlTfrekmTUoieNnyEdOCkx5UxfBjpQ8LnshWHrAZ7CgYHucwvazrKrkSuR0Nw8f7TYiaTY/THtGJlsWSFi32E6+5ogmYoDlzaocpGHx5P9S8Ua9zRplWDp4TxEgRrBIowwZazdAje/YDhqHLwlLpPcYSxDtU0V/rQ27V2n9TOERWtv0D5QPnAgwerBK25TIKGPdmyoyMJjJKp4eR4kiMH89VhHDNMIaxb5DKUPRdYuoyGGYD7NT4mi0+I6vu95hsmdWrQ9S4Zp1Wxb+iMePikwH2UntTUM1194YtJKKfLhd5DiXmYqpcd0lIImUqLVl2p6m8O5d486IfdcF8uoxxJZDy6im95ifxhCCBxpNIHW8HBkNxNJCD0+V8bDyjKS9QTZiZnWViF6vEBS9mHa8xvY/JLh4a9m1oFFPlXSWusnvJMfnydwNJl8ER78I47fccc70D0lwnrIrzjr1iY1D2w9h3FBjy9OZab5BOdCmhJSCbnw1cSsQPfGCUAQjeOP5J40Kz8/iveaO3qbT8kiR47iOi87ZzAzQq4PS7d13QB7+ycIHzdc+tGnwaSRw0heUPAIayYnW4joFM=
