# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TripodVideoNinja | Krishna Bhamidipati
email: email@krishna.video
description: 'Freelance videographer specializing in recording and streaming of classical music concerts.'
baseurl: ''
url: http://tripodvideo.ninja
twitter_username: tripodninja
#github_username:  jekyll

# Build settings
markdown: kramdown

plugins:
- jekyll-assets
