# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TripodNinja | Krishna Bhamidipati
email: email@krishna.video
description: 'Freelance videographer specializing in recording and streaming of classical music concerts.'
baseurl: ''
url: https://krishna.video
twitter_username: tripodninja
github_username: NaanProphet

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-121779698-1
plugins:
- jekyll-assets
- jekyll-twitter-plugin
