version: '3.6'
services:

  app:
    container_name: krishna.video
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 4000:4000
    restart: always
    env_file: 
    - .env.dev
    command: >
      sh -c "bundle install &&
            sh ./build-dev.sh &&
            bundle exec jekyll serve -w --config _config.yml,_config-dev.yml -H 0.0.0.0"
